repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ['--line-length', '140']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        args: ['--max-line-length=140', '--ignore=F401,F403,F405,F841,E401,E402,E741,W605']
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.720'
#    hooks:
#    -   id: mypy
